project_id = "rdvkwnoeojjvjuknlsjd"

[functions.create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.create-test-family] 
verify_jwt = true

[functions.invite-child]
verify_jwt = true

[functions.email-routing]
verify_jwt = false

[functions.email-routing-enhanced]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = true

[functions.admin-create-family-member]
verify_jwt = true

[functions.admin-remove-family-member]
verify_jwt = true

[functions.send-family-invitation]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true